import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
import Content from "./components/Content";
import Pricing from "./components/Pricing";
import Team from "./components/Team";
import Pelayanan from "./components/Pelayanan";
import KritikSaran from "./components/KritikSaran";
import { Inter } from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: "PST From Anywhere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Header />
        <Hero />
        <Content />
        <Pelayanan />
        <Pricing />
        <Team />
        <KritikSaran />
        <Footer/>
      </body>
    </html>
  );
}
